pyproject.toml

The library itself can run on any OS. Ansys Sound is only Windows based

fix: OS classifier should be OS agnostic

---

doc/changelog.d/103.fixed.md
src/ansys/sound/core/spectral_processing/power_spectral_density.py
src/ansys/sound/core/spectrogram_processing/stft.py
tests/tests_spectrogram_processing/test_spectrogram_processing_stft.py

Added BLACKMAN as an accepted window type in classes PowerSpectralDensity and Stft, in accordance with the returned error message in case of invalid type.
Also removed HANNING from accepted window types in class Stft, for the sake of consistence with class PowerSpectralDensity

fix: Missing BLACKMAN window type in PSD and STFT classes

---

doc/changelog.d/112.documentation.md
doc/source/conf.py

@a-bouth While testing in #111 I noticed the following in CICD logging
This should be related to the fact that Ansys prevents "bots" from accessing its urls. This PR provide a way to "define" Sphinx as an actual user and not a bot.
Another work around would be to ignore Ansys links but you wouldn't see if a link is broken.

docs: add user_agent to check Ansys links

---

.github/workflows/ci_cd.yml
doc/changelog.d/135.fixed.md

[Testing and coverage (Windows)](https://github.com/ansys/pyansys-sound/actions/runs/11206409450/job/31147177563#logs) action is failing due to the ``Set up headless display``.

ci: ``pyvista/setup-headless-display`` started failing

---

.github/workflows/ci_cd.yml
doc/changelog.d/165.maintenance.md

Docker images need to be cleaned not to overload the VM.
This PR add this step within the CICD.

ci: deleting docker images from cicd

---

doc/changelog.d/166.fixed.md
doc/source/api/psychoacoustics.rst
src/ansys/sound/core/psychoacoustics/fluctuation_strength.py
src/ansys/sound/core/psychoacoustics/loudness_iso_532_1_stationary.py
src/ansys/sound/core/psychoacoustics/loudness_iso_532_1_time_varying.py
src/ansys/sound/core/psychoacoustics/prominence_ratio.py
src/ansys/sound/core/psychoacoustics/roughness.py
src/ansys/sound/core/psychoacoustics/sharpness.py
src/ansys/sound/core/psychoacoustics/spectral_centroid.py
src/ansys/sound/core/psychoacoustics/tone_to_noise_ratio.py
src/ansys/sound/core/signal_utilities/apply_gain.py
src/ansys/sound/core/signal_utilities/create_sound_field.py
src/ansys/sound/core/signal_utilities/crop_signal.py
src/ansys/sound/core/signal_utilities/load_wav.py
src/ansys/sound/core/signal_utilities/resample.py
src/ansys/sound/core/signal_utilities/sum_signals.py
src/ansys/sound/core/signal_utilities/write_wav.py
src/ansys/sound/core/signal_utilities/zero_pad.py
src/ansys/sound/core/spectral_processing/power_spectral_density.py
src/ansys/sound/core/spectrogram_processing/isolate_orders.py
src/ansys/sound/core/spectrogram_processing/istft.py
src/ansys/sound/core/spectrogram_processing/stft.py
src/ansys/sound/core/xtract/xtract.py
src/ansys/sound/core/xtract/xtract_denoiser.py
src/ansys/sound/core/xtract/xtract_denoiser_parameters.py
src/ansys/sound/core/xtract/xtract_tonal.py
src/ansys/sound/core/xtract/xtract_tonal_parameters.py
src/ansys/sound/core/xtract/xtract_transient.py
src/ansys/sound/core/xtract/xtract_transient_parameters.py
tests/tests_spectrogram_processing/test_spectrogram_processing_isolate_orders.py

- Remove unnecessary explicit getter when a property is defined.
- Add details and consistency in the property docstring.
- Add return hint for each property
- Clean up unnecessary details in setter docstring (+ some missing argument type hints)
- Remove pragma nocover, as it is no longer necessary
Unrelated:
- Added ``SpectralCentroid`` in doc
- Removed 'hanning' from supported options for ``IsolateOrders.window_type``
- Fixed incomplete type test for ``IsolateOrders.orders``
- Fixed a few errors/typos in docstrings

fix: remove unnecessary explicit getters

---

doc/changelog.d/171.documentation.md
examples/002_load_resample_amplify_write_wav_files.py
src/ansys/sound/core/_pyansys_sound.py
src/ansys/sound/core/psychoacoustics/_psychoacoustics_parent.py
src/ansys/sound/core/psychoacoustics/fluctuation_strength.py
src/ansys/sound/core/psychoacoustics/loudness_iso_532_1_stationary.py
src/ansys/sound/core/psychoacoustics/loudness_iso_532_1_time_varying.py
src/ansys/sound/core/psychoacoustics/prominence_ratio.py
src/ansys/sound/core/psychoacoustics/roughness.py
src/ansys/sound/core/psychoacoustics/sharpness.py
src/ansys/sound/core/psychoacoustics/spectral_centroid.py
src/ansys/sound/core/psychoacoustics/tonality_din_45681.py
src/ansys/sound/core/psychoacoustics/tone_to_noise_ratio.py
src/ansys/sound/core/signal_utilities/apply_gain.py
src/ansys/sound/core/signal_utilities/create_sound_field.py
src/ansys/sound/core/signal_utilities/crop_signal.py
src/ansys/sound/core/signal_utilities/load_wav.py
src/ansys/sound/core/signal_utilities/resample.py
src/ansys/sound/core/signal_utilities/sum_signals.py
src/ansys/sound/core/signal_utilities/zero_pad.py
src/ansys/sound/core/sound_composer/source_spectrum.py
src/ansys/sound/core/sound_power/sound_power_level_iso_3744.py
src/ansys/sound/core/spectral_processing/power_spectral_density.py
src/ansys/sound/core/spectrogram_processing/isolate_orders.py
src/ansys/sound/core/spectrogram_processing/istft.py
src/ansys/sound/core/spectrogram_processing/stft.py
src/ansys/sound/core/xtract/xtract.py
src/ansys/sound/core/xtract/xtract_denoiser.py
src/ansys/sound/core/xtract/xtract_tonal.py
src/ansys/sound/core/xtract/xtract_transient.py

Sort out doc and type hints for numpy arrays
- Clarified all docstrings where numpy arrays were mentioned (eg 'numpy.ndarray' instead of things like 'np.array')
- Replaced all ``numpy.typing.ArrayLike`` type hints by ``numpy.ndarray`` for better clarity (and removed ``numpy.typing`` imports altogether)
Also replaced unnecessary ``Tuple`` (with capital T) type hint from ``typing``, with ``tuple`` (lowercase) from baseline types (in xtract classes)
Note: Replacing ``numpy.typing.ArrayLike`` type hints with ``numpy.ndarray`` changes the displayed "Return type" in the produced doc:
- with ``numpy.typing.ArrayLike`` type hint
- with ``numpy.ndarray`` type hint

docs: sort out doc and type hints for numpy arrays

---

.github/workflows/ci_cd.yml
doc/changelog.d/185.maintenance.md
pyproject.toml

Providing active support for Python 3.13 and dropping support for Python 3.9

chore: supporting Python 3.13 and dropping support for Python 3.9

---

doc/changelog.d/222.maintenance.md
pyproject.toml

Switch project dependencies such that PyAnsys Sound now depends on the under-dev version of PyDPF-Core (instead of the latest release previously)
Also removed unnecessary duplicated PyDPF Core dependency for tests

ci: switch pydpfcore dependency to dev version

---

doc/changelog.d/224.fixed.md
examples/006_calculate_PR_and_TNR.py

Apply the same PSD parameters for TNR/PR calculation as in SAS

fix: apply the same PSD parameters for TNR/PR calculation as in SAS

---

doc/changelog.d/223.fixed.md
src/ansys/sound/core/psychoacoustics/loudness_iso_532_1_stationary.py
src/ansys/sound/core/psychoacoustics/loudness_iso_532_1_time_varying.py
tests/tests_psychoacoustics/test_psychoacoustics_loudness_iso_532_1_stationary.py
tests/tests_psychoacoustics/test_psychoacoustics_loudness_iso_532_1_time_varying.py
tests/tests_psychoacoustics/test_psychoacoustics_sharpness_din_45692.py

Add field type in loudness ISO532-1 (stationary/time-varying)
Adjust tests accordingly
(Also fix a variable name typo in sharpness DIN45692 tests)

fix: add field type in loudness ISO532-1 (stationary/time-varying)

---

doc/changelog.d/227.fixed.md
pyproject.toml

This is unnecessary and leads to issues when installing together with other libraries

fix: avoid the usage of the "egg" concept

---

doc/changelog.d/231.fixed.md
pyproject.toml

Add the package `requests` in the project dependencies, because it is necessary in module `download.py`
It used to be included through the `ansys-dpf-core`, and then `google-api-core`, packages, but it seems it is no longer the case

fix: Explicitly add requests package to project dependencies

---

doc/changelog.d/232.fixed.md
src/ansys/sound/core/psychoacoustics/loudness_iso_532_1_stationary.py
src/ansys/sound/core/psychoacoustics/roughness.py
src/ansys/sound/core/psychoacoustics/tonality_din_45681.py
src/ansys/sound/core/spectral_processing/power_spectral_density.py
tests/tests_psychoacoustics/test_psychoacoustics_tonality_din_45681.py
tests/tests_spectral_processing/test_power_spectral_density.py

Specific loudness' and specific roughness' units were wrongly indicating sone and asper, respectively.
They were fixed to their correct units: sone/Bark, and asper/Bark
Also added power-of-2 requirement for FFT size in `PowerSpectralDensity` and corresponding check
(Also removed DIN45681 calculation details from method `get_output_as_nparray` method as it was unusable as such. The reason is these details are stored in a `GenericDataContainerCollection`, and there is no point outputting these as numpy arrays)

fix: Wrong unit for specific loudness and specific roughness in documentation

---

doc/changelog.d/239.added.md
doc/source/api/psychoacoustics.rst
src/ansys/sound/core/psychoacoustics/__init__.py
src/ansys/sound/core/psychoacoustics/tonality_din_45681.py
src/ansys/sound/core/psychoacoustics/tonality_iso_ts_20065.py
tests/tests_psychoacoustics/test_psychoacoustics_tonality_iso_ts_20065.py

Helper class, test class, and doc update for ISO/TS 20065 tonality 
Also updated/added consistency in DIN 45681 and removed default spectrum/tone index value for the sake of consistency with other indicators

feat: Tonality IS/TS 20065

---

.github/workflows/ci_cd.yml
.pre-commit-config.yaml
doc/changelog.d/245.miscellaneous.md

Removed the `-v` argument when running the Docker, for tests and documentation

ci: Changing CI call to docker container only for tests

---

.github/labeler.yml
.github/labels.yml
doc/changelog.d/265.added.md

According to https://github.com/ansys/pyansys-sound/pull/259, labeler needs to be aligned with GitHub settings.
This PR adds new labels:
- ``examples``
- ``dependencies``
- ``ci/cd``

feat: enhancing labeler

---

doc/changelog.d/259.added.md
examples/009_calculate_tonality_indicators.py
src/ansys/sound/core/examples_helpers/__init__.py
src/ansys/sound/core/examples_helpers/download.py
tests/test_example_helpers.py

New example to demonstrate how to calculate and use the following tonality indicators:
- ISO1996-2
- DIN45681
- ECMA418-1
- ISO/TS 20065
- Aurès
In this example, some calculated values are displayed in the console, and some curves are displayed in graphs. Some explanation are given in the text of the example to guide the reader.

feat: new example that calculates several tonality indicators

---

.github/workflows/ci_cd.yml
doc/changelog.d/271.fixed.md
src/ansys/sound/core/psychoacoustics/loudness_iso_532_2.py
tests/tests_psychoacoustics/test_psychoacoustics_loudness_iso_532_2.py
tests/tests_psychoacoustics/test_psychoacoustics_sharpness_din_45692.py
tests/tests_sound_composer/test_sound_composer_source_control_time.py
tests/tests_xtract/test_xtract_denoiser_parameters.py

Because of a DPF Sound bug (STFT last frame was previously present but not filled), a slight change in the DLL required a test's expected value to be updated.
Automatic noise estimation in Xtract is based on STFT, so this change affected expected values for Xtract denoiser
Unrelated:
- Adapted Loudness ISO 532-2 helper class (and test) following a recent change in DPF Sound where the specific loudness support is now the ERBn-number scale, as opposed to the corresponding center frequency previously (ADO PR #580847 )
- Adapted a `SourceControlTime` test following a DPF Sound improvement where non-SI units are now retrieved when using the `load_wav_sas` operator (ADO PR #583498)
- Adapted expected values for Sharpness DIN 45692 following a bug fix in SAS & DPF Sound (ADO PR #585881)

fix: update autodenoise test reference values following DPF Sound DLL update

---

.github/workflows/ci_cd.yml
.github/workflows/label.yml
doc/changelog.d/281.maintenance.md

Specify a headless matplotlib backend in `ci_cd.yml` to fix (or at least avoid) recurrent, but non-systematic, tcl/tk errors
Unrelated:
- Pin specific ansys/actions  commit SHA instead of "dynamic" version numbers (related to the recently broken smoke tests, see https://github.com/ansys/actions/issues/814)

ci: fix tcl/tk random errors by specifying headless matplotlib backend

---

doc/changelog.d/287.added.md
examples/004_isolate_orders.py
examples/005_xtract_feature.py
src/ansys/sound/core/spectrogram_processing/stft.py

Plotting STFTs would be quite time-consuming, for 2 reasons:
- conversion of STFT data from FieldsContainer to numpy array was inefficient
- when plotting an STFT, this conversion was done twice, when once only would have sufficed
To remedy these:
- conversion now preallocates array memory before looping on the FieldsContainer's fields
- conversion called once only when plotting
More generally, these changes improve computation times in any situation where the STFT data is being retrieved as a numpy array (meaning it also improves computation times for some other example scripts that this PR did not change)
Computation times during CI/CD _before_ these changes:
Computation times during CI/CD _after_ these changes:
(also improved some minor code readability issues)

feat: improve stft plot computation time

---

doc/changelog.d/290.fixed.md
tests/tests_spectrogram_processing/test_spectrogram_processing_stft.py
tests/tests_xtract/test_xtract.py
tests/tests_xtract/test_xtract_denoiser.py
tests/tests_xtract/test_xtract_denoiser_parameters.py

STFT computed in DPF Sound was corrected: an extra wrong frame is removed at the beginning of the STFT.
Tests are updated accordingly: STFT, Xtract

fix: update tests following changes in DPF sound STFT

---

doc/changelog.d/289.added.md
doc/changelog.d/289.test.md
examples/001_initialize_server_and_deal_with_license.py
src/ansys/sound/core/examples_helpers/download.py
src/ansys/sound/core/server_helpers/_connect_to_or_start_server.py
tests/conftest.py

When using a local server, an `InProcess` server is now used by default (as opposed to a `gRPC` server previously).
An additional argument was added to still allow using a local `gRPC` server if needed.
Also, example 001 was modified as the local server test did not work as expected

feat: Use in-process server by default when using local server

---

.github/workflows/docker_cleanup.yml
doc/changelog.d/296.added.md
doc/changelog.d/296.maintenance.md

Added a new workflow, run manually or scheduled every Sunday at 2am UTC, that cleans up docker images older than 15 days.
Exceptions are official releases (eg `25.2`) and `latest`

feat: old docker image housekeeping

---

.github/workflows/ci_cd.yml
doc/changelog.d/316.miscellaneous.md
tests/tests_xtract/test_xtract.py

Starting with release 25.2, every CI/CD run will test against past official DPF Sound releases, in addition to the latest package.
This is managed in the `TEST_DPF_SOUND_MATRIX` environment variable defined at the start of `ci_cd.yml`
Additionally the (unique) image used for doc build is also stored in an environment variable `DOCUMENTATION_DPF_SOUND_TAG` and shall be updated for each release
Also fixed an xtract test that would not pass in 25.2 (omitted in the previous STFT bug fix PR)

ci: run CI/CD tests on all past official releases, in addition to the latest package

---

.github/workflows/ci_cd.yml
doc/changelog.d/320.miscellaneous.md

New release has not been deployed to GitHub because this job was missing to the CICD.
This should fix it.

ci: adding ``release to github`` in cicd

---

.github/workflows/ci_cd.yml
doc/changelog.d/323.miscellaneous.md

Some changes have been made in the ``check-vulnerabilities`` action. You can now pass a ``dev-mode`` argument in order to have a unique job in your workflow file. You can have a look at the action documentation [here](https://actions.docs.ansys.com/version/stable/vulnerability-actions/index.html#examples).
This PR applies those latest changes

ci: update the ``check-vulnerabilities`` action
